package broker

import "strings"

// firstLine returns the first line of s, sanitized, for a sane commit subject
// from an attacker-influenced instruction. Strips control characters and
// ANSI escapes (they'd visually corrupt `git log` and terminal output), and
// drops a leading '-' so the subject can't be confused for a git option
// when re-used in some future tool. Capped at 72 chars.
func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		// Keep printable ASCII + a tolerant unicode range (no controls).
		if r >= 0x20 && r != 0x7f {
			b.WriteRune(r)
		}
	}
	out := strings.TrimSpace(b.String())
	for len(out) > 0 && out[0] == '-' {
		out = strings.TrimSpace(out[1:])
	}
	if out == "" {
		out = "agent task"
	}
	if r := []rune(out); len(r) > 72 {
		out = string(r[:72])
	}
	return out
}

// prContent derives a PR title and body from the task instruction. Title is the
// first line, clipped to 72 chars (PR titles must stay short). Body is the
// instruction plus a drydock provenance footer, capped at ~4 KB so it never
// blows argv limits (the full instruction is preserved in the task audit). An
// empty instruction yields ("",""), so adapters fall back to the CLI's --fill.
func prContent(instruction, taskID string) (title, body string) {
	if strings.TrimSpace(instruction) == "" {
		return "", ""
	}
	title = firstLine(instruction)
	if r := []rune(title); len(r) > 72 {
		title = string(r[:71]) + "…"
	}
	const bodyCap = 4096
	body = instruction
	if len(body) > bodyCap {
		body = body[:bodyCap] + "\n\n[truncated — full instruction in the drydock task audit]"
	}
	body += "\n\n---\nGenerated by drydock (task " + taskID + ")."
	return title, body
}

// safeErr renders an error for reflection in an HTTP response body. err.Error()
// can carry attacker-influenced bytes (agent stderr, container-CLI output);
// reflecting those raw makes upstream SIEM ingestion brittle and lets a clever
// agent inject ANSI escapes into operator terminals. Strip non-printables and
// cap.
func safeErr(err error) string {
	if err == nil {
		return ""
	}
	return safeStr(err.Error())
}

// safeStr strips non-printable bytes from operator-reflected text. Any output
// that traces back to the agent (its stdout/stderr, a distilled audit line) can
// carry attacker-influenced bytes; reflecting them raw lets a clever agent
// inject ANSI escapes into operator terminals. Strip non-printables and cap.
func safeStr(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r >= 0x20 && r != 0x7f {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if len(out) > 200 {
		out = out[:200] + "…"
	}
	return out
}

// errorEvent builds a terminal error event. hint may be empty.
func errorEvent(taskID, reason, hint string) map[string]any {
	ev := map[string]any{"event": "error", "task_id": taskID, "reason": reason}
	if hint != "" {
		ev["hint"] = hint
	}
	return ev
}
