package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// repoRoot walks up from the test's cwd to the module root (where go.mod is).
func repoRoot(t *testing.T) string {
	t.Helper()
	d, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(d, "go.mod")); err == nil {
			return d
		}
		p := filepath.Dir(d)
		if p == d {
			t.Fatal("go.mod not found")
		}
		d = p
	}
}

// TestNoStaleVersion fails if any shipped doc/site file mentions an old version.
// The version moved to v0.3.0; nothing user-facing should still say v0.2.0.
func TestNoStaleVersion(t *testing.T) {
	root := repoRoot(t)
	files := []string{"README.md", "site/index.html"}
	docs, _ := filepath.Glob(filepath.Join(root, "site/docs/*.md"))
	for _, d := range docs {
		files = append(files, d[len(root)+1:])
	}
	for _, f := range files {
		b, err := os.ReadFile(filepath.Join(root, f))
		if err != nil {
			continue
		}
		if strings.Contains(string(b), "v0.2.0") {
			t.Errorf("%s still references v0.2.0 (current is v0.3.0)", f)
		}
	}
}

var hrefRe = regexp.MustCompile(`(?:href|src)="([^"#:?][^":]*?)(?:#[^"]*)?"`)

// TestLandingInternalLinksResolve checks every relative href/src on the landing
// page resolves: a docs/*.html target maps to its docs/*.md source (the HTML is
// generated by `make docs`), anything else must exist as a file under site/.
func TestLandingInternalLinksResolve(t *testing.T) {
	root := repoRoot(t)
	b, err := os.ReadFile(filepath.Join(root, "site/index.html"))
	if err != nil {
		t.Fatal(err)
	}
	for _, m := range hrefRe.FindAllStringSubmatch(string(b), -1) {
		target := m[1]
		if strings.HasPrefix(target, "//") || strings.HasPrefix(target, "http") || strings.HasPrefix(target, "mailto") {
			continue
		}
		// A generated docs page: verify its Markdown source exists instead.
		if strings.HasPrefix(target, "docs/") && strings.HasSuffix(target, ".html") {
			src := filepath.Join(root, "site", strings.TrimSuffix(target, ".html")+".md")
			if _, err := os.Stat(src); err != nil {
				t.Errorf("landing links docs page %q with no Markdown source %q", target, src)
			}
			continue
		}
		if _, err := os.Stat(filepath.Join(root, "site", target)); err != nil {
			t.Errorf("landing page links missing asset: %q", target)
		}
	}
}
