package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// repoRoot walks up from the test's cwd to the module root (where go.mod is).
func repoRoot(t *testing.T) string {
	t.Helper()
	d, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(d, "go.mod")); err == nil {
			return d
		}
		p := filepath.Dir(d)
		if p == d {
			t.Fatal("go.mod not found")
		}
		d = p
	}
}

// currentVersion returns the newest released version heading in CHANGELOG.md
// (the single source of truth). "## Unreleased" is skipped by the vX.Y.Z shape.
func currentVersion(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(repoRoot(t), "CHANGELOG.md"))
	if err != nil {
		t.Fatalf("read CHANGELOG.md: %v", err)
	}
	m := regexp.MustCompile(`(?m)^## (v\d+\.\d+\.\d+)`).FindStringSubmatch(string(b))
	if m == nil {
		t.Fatal("no released version heading (## vX.Y.Z) in CHANGELOG.md")
	}
	return m[1]
}

// TestReadmeStatusVersionCurrent pins the README status line to the current
// release. This is the version claim that goes stale (it did: v0.4.0 lingered
// two releases). The prior guard was frozen at a literal "v0.2.0" and so caught
// nothing after v0.3.0; deriving from CHANGELOG keeps it honest automatically.
func TestReadmeStatusVersionCurrent(t *testing.T) {
	root := repoRoot(t)
	want := currentVersion(t)
	b, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	m := regexp.MustCompile(`(?m)^>\s*\*\*Status:[^(]*\((v\d+\.\d+\.\d+)\)`).FindStringSubmatch(string(b))
	if m == nil {
		t.Fatal("README.md has no '> **Status: … (vX.Y.Z)** ' line")
	}
	if m[1] != want {
		t.Errorf("README status says %s but current release is %s (CHANGELOG)", m[1], want)
	}
}

var hrefRe = regexp.MustCompile(`(?:href|src)="([^"#:?][^":]*?)(?:#[^"]*)?"`)

// TestLandingInternalLinksResolve checks every relative href/src on the landing
// page resolves: a docs/*.html target maps to its docs/*.md source (the HTML is
// generated by `make docs`), anything else must exist as a file under site/.
func TestLandingInternalLinksResolve(t *testing.T) {
	root := repoRoot(t)
	b, err := os.ReadFile(filepath.Join(root, "site/index.html"))
	if err != nil {
		t.Fatal(err)
	}
	for _, m := range hrefRe.FindAllStringSubmatch(string(b), -1) {
		target := m[1]
		if strings.HasPrefix(target, "//") || strings.HasPrefix(target, "http") || strings.HasPrefix(target, "mailto") {
			continue
		}
		// The threat model docs page is rendered from the canonical root file.
		if target == "docs/threat-model.html" {
			if _, err := os.Stat(filepath.Join(root, "THREAT_MODEL.md")); err != nil {
				t.Errorf("landing links the threat model but THREAT_MODEL.md is missing")
			}
			continue
		}
		// A generated docs page: verify its Markdown source exists instead.
		if strings.HasPrefix(target, "docs/") && strings.HasSuffix(target, ".html") {
			src := filepath.Join(root, "site", strings.TrimSuffix(target, ".html")+".md")
			if _, err := os.Stat(src); err != nil {
				t.Errorf("landing links docs page %q with no Markdown source %q", target, src)
			}
			continue
		}
		if _, err := os.Stat(filepath.Join(root, "site", target)); err != nil {
			t.Errorf("landing page links missing asset: %q", target)
		}
	}
}
